"use client";
import Head from "next/head.js";
import { useEffect, useRef } from "react";
import Image from "next/image";
import styles from "./styles/Home.module.css";
import igicon from "../public/assets/img/instagram.png";
import Form from "./components/Form.jsx";
import { gsap } from "gsap";
import Link from "next/link.js";

export default function Home() {
  const formRef = useRef(null);
  const scrollToRef = () =>
    formRef.current.scrollIntoView({ behavior: "smooth" });
  const heroRef = useRef(null);
  const h1Ref = useRef(null);
  const btnRef = useRef(null);

  useEffect(() => {
    let tl = gsap.timeline({
      defaults: {
        ease: "power2",
        duration: 2,
      },
    });
    tl.to(heroRef.current, {
      clipPath: "polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)",
    })
      .to(
        h1Ref.current,
        {
          duration: 1.4,
          y: 0,
        },
        "-=1"
      )
      .to(
        btnRef.current,
        {
          duration: 1.4,
          opacity: 1,
        },
        "-=1"
      );
  });

  return (
    <>
      <Head>
        <title>Socal Beauty Med Spa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero} ref={heroRef}>
          <div className="mask">
            <h1 className={styles.h1} ref={h1Ref}>
              Boost Your Natural Beauty
            </h1>
          </div>
          <Link
            className={styles.btn}
            ref={btnRef}
            href={"https://www.vagaro.com/socalbeautymedspa"}
            target="_blank"
          >
            Book Now
          </Link>
        </div>
        <h2 className={styles.h2}>
          Indulge in Elite Med Spa Services at Covina&apos;s Premier
          Destination.
        </h2>
        <div className={`${styles["section"]} ${styles["logo-bg"]}`}>
          <h3 className={styles.h3}>About Us</h3>
          <p className={styles.p}>
            We are your one-stop destination for all things health, wellness,
            and aesthetics in Covina, California. Our mission is to help our
            clients look and feel their best by providing cutting-edge
            treatments and personalized care.
          </p>
          <p className={styles.p}>
            Our supervised weight loss program, featuring the revolutionary
            medication Semaglutide, can help you achieve your weight loss goals
            in a safe and effective manner. At So Cal Beauty Med Spa, we believe
            that taking care of yourself should be a fun and enjoyable
            experience, which is why we strive to create a welcoming and
            family-like atmosphere.
          </p>
          <p className={styles.p}>
            Whether you are a first-timer or a regular client, we are committed
            to providing you with the highest quality of care and the best
            possible results.
          </p>
          <p className={styles.p}>
            Book your appointment with us today and start your journey to a
            healthier, more beautiful you!
          </p>
        </div>
        <div className={styles.section} ref={formRef}>
          <h3 className={styles.h3}>Send A Message</h3>
          <hr className={styles.hr} />
          <Form />
        </div>
        <div className={styles.info}>
          <div className={styles.address}>
            <a
              className={styles.link}
              href="https://www.google.com/maps/search/?api=1&query=164+W+Badillo+St.%2C+Covina%2C+CA+91723"
            >
              164 W Badillo St.
            </a>
            <a
              className={styles.link}
              href="https://www.google.com/maps/search/?api=1&query=164+W+Badillo+St.%2C+Covina%2C+CA+91723"
            >
              Covina, CA 91723
            </a>
          </div>
          <a className={styles.link} href="mailto:socalbeautymedspa@gmail.com">
            socalbeautymedspa@gmail.com
          </a>
          <a className={styles.link} href="tel:+1-626-498-7631">
            626-498-7631
          </a>
        </div>
        <div className={styles.info}>
          <a href="https://www.instagram.com/socalbeautymedspa/">
            <Image className={styles.icon} src={igicon} alt="instagram" />
          </a>
        </div>
      </main>
    </>
  );
}
