import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useRef } from "react";
import igicon from "@/public/assets/icons/instagram.png";
import emailjs from "@emailjs/browser";

export default function Home() {
	const ref = useRef(null);
	const scrollToRef = () => ref.current.scrollIntoView({ behavior: "smooth" });
	const sendEmail = (e) => {
		e.preventDefault();

		emailjs
			.sendForm(
				"service_9efmxmg",
				"template_tojkqmu",
				e.target,
				"rwOAXyAKAo4ZTTkGO"
			)
			.then(
				(result) => {
					console.log(result.text);
				},
				(error) => {
					console.log(error.text);
				}
			);
		e.target.reset();
		setSubmitted(true);
	};

	return (
		<>
			<Head>
				<title>Socal Beauty Med Spa</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.hero}>
					<h1 className={styles.h1}>
						Boost Your Natural Beauty At The Top Med Spa In Covina
					</h1>
					<button className={styles.btn} onClick={scrollToRef}>
						Book Now
					</button>
				</div>
				<div className={`${styles["section"]} ${styles["logo-bg"]}`}>
					<h2 className={styles.h2}>Welcome</h2>
					<p className={styles.p}>
						We are your one-stop destination for all things health, wellness,
						and aesthetics in Covina, California. Our mission is to help our
						clients look and feel their best by providing cutting-edge
						treatments and personalized care.
					</p>
					<p className={styles.p}>
						Our supervised weight loss program, featuring the revolutionary
						medication Semaglutide, can help you achieve your weight loss goals
						in a safe and effective manner. At So Cal Beauty Med Spa, we believe
						that taking care of yourself should be a fun and enjoyable
						experience, which is why we strive to create a welcoming and
						family-like atmosphere.
					</p>
					<p className={styles.p}>
						Whether you are a first-timer or a regular client, we are committed
						to providing you with the highest quality of care and the best
						possible results.
					</p>
					<p className={styles.p}>
						Book your appointment with us today and start your journey to a
						healthier, more beautiful you!
					</p>
				</div>
				<div className={styles.section}>
					{/* <h2 className={styles.h2}>Mega Sale</h2>
					<Image
						className={styles["img-large"]}
						src={promoimg}
						alt={"Mega Sale"}
					/> */}
				</div>
				<div className={styles.section}>
					<h2 className={styles.h2}>Request A Booking</h2>
					<hr className={styles.hr} />
					<form
						className={styles.form}
						action=""
						onSubmit={sendEmail}
						ref={ref}
					>
						<input
							className={styles.input}
							type="text"
							placeholder={"Full Name"}
							name="fullName"
							required
						/>
						<input
							className={styles.input}
							type="email"
							placeholder={"Email Address"}
							name="email"
							required
						/>
						<input
							className={styles.input}
							type="tel"
							placeholder={"Phone Number"}
							name="phone"
							required
						/>
						<input
							className={styles.input}
							type="text"
							placeholder={"Message"}
							name="message"
							required
						/>
						<button className={styles.btn}>Submit</button>
					</form>
				</div>
				<div className={`${styles["section"]} ${styles["info"]}`}>
					<a className={styles.link} href="tel:+1-626-498-7631">
						626-498-7631
					</a>
					<a className={styles.link} href="mailto:socalbeautymedspa@gmail.com">
						socalbeautymedspa@gmail.com
					</a>
					<a
						className={styles.link}
						href="https://www.google.com/maps/search/?api=1&query=164+W+Badillo+St.%2C+Covina%2C+CA+91723"
					>
						164 W Badillo St.
					</a>
					<a
						className={styles.link}
						href="https://www.google.com/maps/search/?api=1&query=164+W+Badillo+St.%2C+Covina%2C+CA+91723"
					>
						Covina, CA 91723
					</a>
					<a href="https://www.instagram.com/socalbeautymedspa/">
						<Image className={styles.icon} src={igicon} alt="instagram" />
					</a>
				</div>
			</main>
		</>
	);
}
